# NIFTY 100 Stocks List
# Top 100 liquid stocks from NSE

NIFTY_100_STOCKS = [
    # NIFTY 50 (First 50)
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'SBIN.NS',
    'INFOSY.NS', 'HINDUNILVR.NS', 'BAJAJFINSV.NS', 'MARUTI.NS', 'ASIANPAINT.NS',
    'SUNPHARMA.NS', 'WIPRO.NS', 'TECHM.NS', 'POWERGRID.NS', 'NTPC.NS',
    'COALINDIA.NS', 'ONGC.NS', 'EICHERMOT.NS', 'BAJAJ-AUTO.NS', 'HEROMOTOCO.NS',
    'INDUSTOWER.NS', 'TITAN.NS', 'NESTLEIND.NS', 'ITC.NS', 'JSWSTEEL.NS',
    'TATASTEEL.NS', 'HINDALCO.NS', 'GAIL.NS', 'ADANIPORTS.NS', 'APOLLOHOSP.NS',
    'BHARTIARTL.NS', 'BPCL.NS', 'BRITANNIA.NS', 'CIPLA.NS', 'DRREDDY.NS',
    'ESCORTS.NS', 'GICRE.NS', 'GODREJCP.NS', 'HAVELLS.NS', 'HPCL.NS',
    'IOC.NS', 'JSWENERGY.NS', 'KOTAKBANK.NS', 'LT.NS', 'MRF.NS',
    'NATIONALUM.NS', 'PESAAONE.NS', 'PIDILITIND.NS', 'SHREECEM.NS', 'TATACONSUM.NS',
    
    # NIFTY Next 50 (Next 50, selecting liquid ones)
    'ADANIGREEN.NS', 'ADANITRANS.NS', 'ASHOKLEY.NS', 'AXISBANK.NS', 'BANDHANBNK.NS',
    'BANKBARODA.NS', 'BOSCHLTD.NS', 'CHOLAFIN.NS', 'COLPAL.NS', 'CONCOR.NS',
    'CUMMINSIND.NS', 'DABUR.NS', 'DMART.NS', 'EXIDEIND.NS', 'FEDERALBNK.NS',
    'FESTALLOY.NS', 'GLENMARK.NS', 'GMRINFRA.NS', 'GRAPHITE.NS', 'GRINDWELL.NS',
    'HDFC.NS', 'HITACHIHP.NS', 'HONAUT.NS', 'IBULHSGFIN.NS', 'IDBI.NS',
    'INDIGO.NS', 'IPCALAB.NS', 'IRB.NS', 'JBCHOT.NS', 'JUSTDIAL.NS',
    'KALYANKJIL.NS', 'KANSAINER.NS', 'KARURVYSYA.NS', 'LUPIN.NS', 'M&MFIN.NS',
    'MANAPPURAM.NS', 'MINDTREE.NS', 'MOTHERSON.NS', 'MPHASIS.NS', 'MUTHOOTFIN.NS',
    'NMDC.NS', 'ODISHATELE.NS', 'PAGEIND.NS', 'PARIBAS.NS', 'PARKHOTELS.NS'
]

def get_nifty_100():
    """Return list of NIFTY 100 stocks"""
    return NIFTY_100_STOCKS
